server {
  host = "127.0.0.1"
  port = 8002
}

monitor {
  timeout = 1440
}

bot {
  uri: "http://localhost:8001"
}

doobie {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/db"
  user = "uesr"
  password = "password"
}

slick = {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/db"
  user = "postgres"
  password = "password"

  connectionPool = disabled
}

access-type: "SQL"
